apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
metadata:
  name: guestbook-ui-3
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
