apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualNetwork
metadata:
  name: crossplane-virtualnetwork
spec:
  forProvider:
    addressSpace:
      - 10.0.0.0/16
    location: "East us 2"
    resourceGroupName: pep-rg-eus